---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}
  namespace: {{ .Release.Namespace }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "managed-identity-wallets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "managed-identity-wallets.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      imagePullSecrets:
        - name: {{ .Values.image.secret }}
      containers:
      - name: catenax-managed-identity-wallets
        {{- if .Values.image.registry }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}
        {{- else }}
        image: {{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}
        {{- end }}
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: {{ .Chart.AppVersion }}
        - name: ALLOW_EMPTY_PASSWORD
          value: {{ .Values.allowEmptyPassword | default "no" }}
        - name: CX_DB_JDBC_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: cx-db-jdbc-url
        - name: CX_DB_JDBC_DRIVER
          value: {{ .Values.db.jdbcDriver }}
        - name: CX_AUTH_JWKS_URL
          value: {{ .Values.auth.jwksUrl }}
        - name: CX_AUTH_ISSUER_URL
          value: {{ .Values.auth.issuerUrl }}
        - name: CX_AUTH_REALM
          value: {{ .Values.auth.realm }}
        - name: CX_AUTH_ROLE
          value: {{ .Values.auth.role }}
        - name: CX_AUTH_ROLE_MAPPINGS
          value: {{ .Values.auth.roleMappings }}
        - name: CX_AUTH_RESOURCE_ID
          value: {{ .Values.auth.resourceId }}
        - name: CX_AUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: cx-auth-client-id
        - name: CX_AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: cx-auth-client-secret
        - name: CX_AUTH_REDIRECT_URL
          value: {{ .Values.auth.redirectUrl }}
        - name: BPDM_DATAPOOL_URL
          value: {{ .Values.datapool.url }}
        - name: BPDM_AUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: bpdm-auth-client-id
        - name: BPDM_AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: bpdm-auth-client-secret
        - name: BPDM_AUTH_GRANT_TYPE
          value: {{ .Values.datapool.grantType }}
        - name: BPDM_AUTH_SCOPE
          value: {{ .Values.datapool.scope }}
        - name: BPDM_AUTH_URL
          value: {{ .Values.datapool.authUrl }}
        - name: BPDM_PULL_DATA_AT_HOUR
          value: {{ .Values.datapool.refreshHour | quote }}
        - name: ACAPY_NETWORK_IDENTIFIER
          value: {{ .Values.acapy.networkIdentifier }}  
        - name: ACAPY_API_ADMIN_URL
          value: {{ .Values.acapy.mt.adminUrl }}
        - name: ACAPY_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-admin-api-key
        - name: ACAPY_BASE_WALLET_API_ADMIN_URL
          value: {{ .Values.acapy.endorser.adminUrl }}
        - name: ACAPY_BASE_WALLET_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-admin-api-key
        - name: CX_BPN
          value: {{ .Values.wallet.baseWalletBpn }}
        - name: CX_SHORT_DID
          value: {{ .Values.wallet.baseWalletShortDid }} 
        - name: CX_VERKEY
          value: {{ .Values.wallet.baseWalletVerkey }} 
        - name: CX_NAME
          value: {{ .Values.wallet.baseWalletName }} 
        - name: REVOCATION_URL
          value: {{ .Values.revocation.revocationServiceUrl }}
        - name: REVOCATION_CREATE_STATUS_LIST_CREDENTIAL_AT_HOUR
          value: {{ .Values.revocation.refreshHour | quote }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
      - name: catenax-revocation-service
        image: {{ .Values.revocationService.imageName }}:{{ .Values.revocationService.tag }}
        imagePullPolicy: Always
        env:
        - name: QUARKUS_HTTP_PORT
          value: {{ .Values.revocationService.port | quote }}
        - name: QUARKUS_HTTP_ACCESS_LOG_ENABLED
          value: {{ .Values.revocationService.httpAccessLog | quote | default "false" }}
        - name: QUARKUS_DATASOURCE_JDBC_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: cx-db-jdbc-url
        - name: REVOCATION_BASE_URL
          value: {{ .Values.revocationService.baseUrlForCredentialList }}
        - name: REVOCATION_MIN_ISSUE_INTERVAL
          value: {{ .Values.revocationService.minIssueInterval | quote}}
        - name: QUARKUS_REST_CLIENT_SSI_ISSUANCE_API_URL
          value: {{ .Values.revocationService.clientIssuanceApiUrl }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8086
      - name: catenax-endorser-acapy
        image: {{ .Values.acapy.imageName }}:{{ .Values.acapy.tag }}
        env:
        - name: WALLET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-wallet-key
        - name: AGENT_WALLET_SEED
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-agent-wallet-seed
        - name: LEDGER_URL
          value: {{ .Values.acapy.endorser.ledgerUrl }}
        - name: LABEL
          value: {{ .Values.acapy.endorser.label }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-jwt-secret
        - name: ACAPY_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-admin-api-key
        - name: LOG_LEVEL
          value: {{ .Values.acapy.endorser.logLevel }}
        - name: ACAPY_ENDPOINT_PORT
          value: {{ .Values.acapy.endorser.endpointPort | quote }}
        - name: ACAPY_ENDPOINT_URL
          value: {{ .Values.acapy.endorser.endpointUrl }}
        - name: ACAPY_ADMIN_PORT
          value: {{ .Values.acapy.endorser.adminPort | quote }}
        - name: DB_HOST
          {{- if .Values.acapypostgresql.enabled }}
          value: {{ include "acapyPostgresContext" (list $ "postgresql.primary.fullname") }}
          {{- else }}
          value: {{ .Values.acapy.endorser.databaseHost }}
          {{- end }}
        - name: DB_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-db-account
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-db-password
        - name: DB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-db-admin
        - name: DB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-db-admin-password
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8000
        command: ["/bin/bash"]
        args: ["-c", "aca-py start \
          -e $(ACAPY_ENDPOINT_URL) \
          --auto-provision \
          --inbound-transport http '0.0.0.0' $(ACAPY_ENDPOINT_PORT) \
          --outbound-transport http \
          --admin '0.0.0.0' $(ACAPY_ADMIN_PORT) \
          --wallet-name AcapyCatenaXEndorserWallet \
          --wallet-type askar \
          --wallet-key $(WALLET_KEY) \
          --wallet-storage-type postgres_storage
          --wallet-storage-config '{\"url\":\"$(DB_HOST):5432\",\"max_connections\":5}'
          --wallet-storage-creds '{\"account\":\"$(DB_ACCOUNT)\",\"password\":\"$(DB_PASSWORD)\",\"admin_account\":\"$(DB_ADMIN_USER)\",\"admin_password\":\"$(DB_ADMIN_PASSWORD)\"}'
          --seed $(AGENT_WALLET_SEED) \
          --genesis-url $(LEDGER_URL)/genesis \
          --label $(LABEL) \
          --admin-api-key $(ACAPY_ADMIN_API_KEY) \
          --auto-ping-connection \
          --jwt-secret $(JWT_SECRET) \
          --public-invites \
          --endorser-protocol-role endorser \
          --auto-endorse-transactions \
          --log-level $(LOG_LEVEL)"
        ]
      - name: catenax-mt-acapy
        image: {{ .Values.acapy.imageName }}:{{ .Values.acapy.tag }}
        env:
        - name: WALLET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-wallet-key
        - name: AGENT_WALLET_SEED
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-agent-wallet-seed
        - name: LEDGER_URL
          value: {{ .Values.acapy.mt.ledgerUrl }}
        - name: LABEL
          value: {{ .Values.acapy.mt.label }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-jwt-secret
        - name: ACAPY_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-admin-api-key
        - name: LOG_LEVEL
          value: {{ .Values.acapy.mt.logLevel }}
        - name: ACAPY_ENDPOINT_PORT
          value: {{ .Values.acapy.mt.endpointPort | quote }}
        - name: ACAPY_ENDPOINT_URL
          value: {{ .Values.acapy.mt.endpointUrl }}
        - name: ACAPY_ADMIN_PORT
          value: {{ .Values.acapy.mt.adminPort | quote }}
        - name: DB_HOST
          {{- if .Values.acapypostgresql.enabled }}
          value: {{ include "acapyPostgresContext" (list $ "postgresql.primary.fullname") }}
          {{- else }}
          value: {{ .Values.acapy.mt.databaseHost }}
          {{- end }}
        - name: DB_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-db-account
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-db-password
        - name: DB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-db-admin
        - name: DB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-db-admin-password
        - name: ACAPY_ENDORSER_PUBLIC_DID
          value: {{ .Values.acapy.mt.endorserPublicDid }}
        - name: ACAPY_WEBHOOK_URL
          value: {{ .Values.acapy.mt.webhookUrl }}  
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8003   
        command: ["/bin/bash"]
        args: ["-c", "aca-py start \
          -e $(ACAPY_ENDPOINT_URL) \
          --auto-provision \
          --inbound-transport http '0.0.0.0' $(ACAPY_ENDPOINT_PORT) \
          --outbound-transport http \
          --admin '0.0.0.0' $(ACAPY_ADMIN_PORT) \
          --wallet-name AcapyCatenaXManagedWallet \
          --wallet-type askar \
          --wallet-key $(WALLET_KEY) \
          --wallet-storage-type postgres_storage
          --wallet-storage-config '{\"url\":\"$(DB_HOST):5432\",\"max_connections\":5}'
          --wallet-storage-creds '{\"account\":\"$(DB_ACCOUNT)\",\"password\":\"$(DB_PASSWORD)\",\"admin_account\":\"$(DB_ADMIN_USER)\",\"admin_password\":\"$(DB_ADMIN_PASSWORD)\"}'
          --seed $(AGENT_WALLET_SEED) \
          --genesis-url $(LEDGER_URL)/genesis \
          --label $(LABEL) \
          --admin-api-key $(ACAPY_ADMIN_API_KEY) \
          --auto-ping-connection \
          --jwt-secret $(JWT_SECRET) \
          --multitenant \
          --multitenant-admin \
          --public-invites \
          --webhook-url $(ACAPY_WEBHOOK_URL) \
          --endorser-protocol-role author \
          --endorser-alias endorser \
          --endorser-public-did $(ACAPY_ENDORSER_PUBLIC_DID) \
          --auto-request-endorsement \
          --auto-write-transactions \
          --auto-promote-author-did \
          --log-level $(LOG_LEVEL)"
        ]
