version: 3

dotenv:
  - 'dev.env'

tasks:
  startKotlinApp:
    desc: start the MIW Kotlin application
    dir: ./
    cmds:
      - set -a; source dev.env; set +a
      - ./gradlew run
  
  runDevEnv:
    desc: Spin up local Docker environment
    dir: dev-assets/dev-containers
    cmds:
      - docker-compose up

  helmUnitTest:
    desc: Executes helm unittests
    dir: charts/managed-identity-wallets
    cmds:
      - helm unittest .
