version: 3

dotenv:
  - 'dev.env'

tasks:
  startDevEnv:
    desc: Start up local Docker environment
    dir: dev-assets/dev-containers
    cmds:
      - docker-compose up -d

  stopDevEnv:
    desc: Stop local Docker environment
    dir: dev-assets/dev-containers
    cmds:
      - docker-compose down

  stopDevEnvAndRemoveVolumes:
    desc: Stop local Docker environment
    dir: dev-assets/dev-containers
    cmds:
      - docker-compose down -v

  helmUnitTest:
    desc: Executes helm unittests
    dir: charts/managed-identity-wallets
    cmds:
      - helm unittest .

  startKotlinApp:
    desc: start the MIW Kotlin application
    deps: [startDevEnv]
    dir: ./
    cmds:
      - set -a; source dev.env; set +a
      - ./gradlew run