/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.42).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.eclipse.tractusx.managedidentitywallets.swagger.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.eclipse.tractusx.managedidentitywallets.swagger.model.DidDocumentDto;
import org.eclipse.tractusx.managedidentitywallets.swagger.model.ExceptionResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.processing.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-05-24T08:44:38.406697803Z[GMT]")
@Validated
@Tag(name = "DidDocument", description = "the DidDocument API")
public interface DidDocumentApi {

    @Operation(summary = "Resolve DID Document", description = "Resolve the DID document for a given DID or BPN")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "The resolved DID Document", content = @Content(schema = @Schema(implementation = DidDocumentDto.class))),
            @ApiResponse(responseCode = "400", description = "The input does not comply to the syntax requirements", content = @Content(schema = @Schema(implementation = ExceptionResponse.class))),
            @ApiResponse(responseCode = "404", description = "The required entity does not exists", content = @Content(schema = @Schema(implementation = ExceptionResponse.class)))})
    @RequestMapping(value = "/api/didDocuments/{identifier}",
            produces = "application/json",
            method = RequestMethod.GET)
    ResponseEntity<DidDocumentDto> apiDidDocumentsIdentifierGet(@Parameter(required = true) @PathVariable("identifier") String identifier);

}

