/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.42).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.eclipse.tractusx.managedidentitywallets.swagger.api;

import io.swagger.annotations.*;
import org.eclipse.tractusx.managedidentitywallets.swagger.model.DidDocumentDto;
import org.eclipse.tractusx.managedidentitywallets.swagger.model.ExceptionResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.processing.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-05-24T08:44:38.406697803Z[GMT]")
@Validated
@Api(value = "DidDocument", description = "the DidDocument API")
public interface DidDocumentApi {

    @ApiOperation(value = "Resolve DID Document", nickname = "apiDidDocumentsIdentifierGet", notes = "Resolve the DID document for a given DID or BPN", response = DidDocumentDto.class, tags={ "DIDDocument", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The resolved DID Document", response = DidDocumentDto.class),
        @ApiResponse(code = 400, message = "The input does not comply to the syntax requirements", response = ExceptionResponse.class),
        @ApiResponse(code = 404, message = "The required entity does not exists", response = ExceptionResponse.class) })
    @RequestMapping(value = "/api/didDocuments/{identifier}",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<DidDocumentDto> apiDidDocumentsIdentifierGet(@ApiParam(value = "", required=true) @PathVariable("identifier") String identifier);

}

