apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-acapy-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-acapy-2
  template:
    metadata:
      labels:
        app: postgres-acapy-2
    spec:
      securityContext:
        runAsNonRoot: true #requires the container to run without root privilege - fix for Checkov Check ID: CKV_K8S_23
      volumes:
        - name: postgres-pv-acapy-storage
          persistentVolumeClaim:
            claimName: postgres-pv-acapy-claim
      containers:
        # kics-scan ignore-line
        - name: postgres-acapy-2
          image: postgres:11
          securityContext:
            allowPrivilegeEscalation: false #prevents RunAsUser commands to bypass their existing permissions - fix for Checkov Check ID: CKV_K8S_20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-acapy-secret-config
                key: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-acapy-secret-config
                key: user
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv-acapy-storage
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
