auth:
  jwksUrl: "https://centralidp-pen.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs"
  issuerUrl: "https://centralidp-pen.dev.demo.catena-x.net/auth/realms/CX-Central"
  redirectUrl: "https://managed-identity-wallets-pen.dev.demo.catena-x.net/callback"
datapool:
  url: "https://catenax-bpdm-dev.demo.catena-x.net"
  authUrl: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
image:
  tag: "latest-develop"
revocationService:
  baseUrlForCredentialList: "https://managed-identity-wallets.pen.demo.catena-x.net/api/credentials/"
  clientIssuanceApiUrl: "http://localhost:8080"
ingress:
  enabled: true
certificate:
  host: "managed-identity-wallets-pen.dev.demo.catena-x.net"
acapy:
  logLevel: "DEBUG"
  ledgerUrl: "http://dev.greenlight.bcovrin.vonx.io"
  endpointUrl: "https://managed-identity-wallets-pen.dev.demo.catena-x.net:8000/"
  databaseHost: "product-managed-identity-wallets-pen-acapypostgresql"
  secret:
    apikey: <path:managed-identity-wallets/data/pen/managed-identity-wallets-acapy-secrets#acapy-admin-api-key>
    walletseed: <path:managed-identity-wallets/data/pen/managed-identity-wallets-acapy-secrets#acapy-agent-wallet-seed>
    dbaccount: <path:managed-identity-wallets/data/pen/managed-identity-wallets-acapy-secrets#acapy-db-account>
    dbadminuser: <path:managed-identity-wallets/data/pen/managed-identity-wallets-acapy-secrets#acapy-db-admin>
    dbadminpassword: <path:managed-identity-wallets/data/pen/managed-identity-wallets-acapy-secrets#acapy-db-admin-password>
    dbpassword: <path:managed-identity-wallets/data/pen/managed-identity-wallets-acapy-secrets#acapy-db-password>
    jwtsecret: <path:managed-identity-wallets/data/pen/managed-identity-wallets-acapy-secrets#acapy-jwt-secret>
    walletkey: <path:managed-identity-wallets/data/pen/managed-identity-wallets-acapy-secrets#acapy-wallet-key>
managedIdentityWallets:
  secret:
    jdbcurl: <path:managed-identity-wallets/data/pen/managed-identity-wallets-secrets#miw-db-jdbc-url>
    authclientid: <path:managed-identity-wallets/data/pen/managed-identity-wallets-secrets#miw-auth-client-id>
    authclientsecret: <path:managed-identity-wallets/data/pen/managed-identity-wallets-secrets#miw-auth-client-secret>
    bpdmauthclientid: <path:managed-identity-wallets/data/pen/managed-identity-wallets-secrets#bpdm-auth-client-id>
    bpdmauthclientsecret: <path:managed-identity-wallets/data/pen/managed-identity-wallets-secrets#bpdm-auth-client-secret>
postgresql:
  secret:
    password: <path:managed-identity-wallets/data/pen/postgres-managed-identity-wallets-secret-config#password>
    postgrespassword: <path:managed-identity-wallets/data/pen/postgres-managed-identity-wallets-secret-config#postgres-password>
    user: <path:managed-identity-wallets/data/pen/postgres-managed-identity-wallets-secret-config#user>
acapypostgresql:
  secret:
    password: <path:managed-identity-wallets/data/pen/postgres-acapy-secret-config#password>
    postgrespassword: <path:managed-identity-wallets/data/pen/postgres-acapy-secret-config#postgres-password>
    user: <path:managed-identity-wallets/data/pen/postgres-acapy-secret-config#user>
