---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}
  namespace: {{ .Release.Namespace }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "managed-identity-wallets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "managed-identity-wallets.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      imagePullSecrets:
        - name: {{ .Values.image.secret }}
      containers:
      - name: managed-identity-wallets
        {{- if .Values.image.registry }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}
        {{- else }}
        image: {{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}
        {{- end }}
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: {{ .Chart.AppVersion }}
        - name: ALLOW_EMPTY_PASSWORD
          value: {{ .Values.allowEmptyPassword | default "no" }}
        - name: MIW_DB_JDBC_URL
          {{- if .Values.postgresql.useDefaultJdbcUrl }}
          value: {{ include "managed-identity-wallets.jdbcUrl" . }}
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: miw-db-jdbc-url
          {{- end }}
        - name: MIW_DB_JDBC_DRIVER
          value: {{ .Values.db.jdbcDriver }}
        - name: MIW_AUTH_JWKS_URL
          value: {{ .Values.auth.jwksUrl }}
        - name: MIW_AUTH_ISSUER_URL
          value: {{ .Values.auth.issuerUrl }}
        - name: MIW_AUTH_REALM
          value: {{ .Values.auth.realm }}
        - name: MIW_AUTH_ROLE
          value: {{ .Values.auth.role }}
        - name: MIW_AUTH_ROLE_MAPPINGS
          value: {{ .Values.auth.roleMappings }}
        - name: MIW_AUTH_RESOURCE_ID
          value: {{ .Values.auth.resourceId }}
        - name: MIW_AUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: miw-auth-client-id
        - name: MIW_AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: miw-auth-client-secret
        - name: MIW_AUTH_REDIRECT_URL
          value: {{ .Values.auth.redirectUrl }}
        - name: BPDM_DATAPOOL_URL
          value: {{ .Values.datapool.url }}
        - name: BPDM_AUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: bpdm-auth-client-id
        - name: BPDM_AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: bpdm-auth-client-secret
        - name: BPDM_AUTH_GRANT_TYPE
          value: {{ .Values.datapool.grantType }}
        - name: BPDM_AUTH_SCOPE
          value: {{ .Values.datapool.scope }}
        - name: BPDM_AUTH_URL
          value: {{ .Values.datapool.authUrl }}
        - name: BPDM_PULL_DATA_AT_HOUR
          value: {{ .Values.datapool.refreshHour | quote }}
        - name: ACAPY_NETWORK_IDENTIFIER
          value: {{ .Values.acapy.networkIdentifier }}
        - name: ACAPY_API_ADMIN_URL
          value: {{ .Values.acapy.mt.adminUrl }}
        - name: ACAPY_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-admin-api-key
        - name: ACAPY_BASE_WALLET_API_ADMIN_URL
          value: {{ .Values.acapy.endorser.adminUrl }}
        - name: ACAPY_BASE_WALLET_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-admin-api-key
        - name: MIW_BPN
          value: {{ .Values.wallet.baseWalletBpn }}
        - name: MIW_SHORT_DID
          value: {{ .Values.wallet.baseWalletShortDid }}
        - name: MIW_VERKEY
          value: {{ .Values.wallet.baseWalletVerkey }}
        - name: MIW_NAME
          value: {{ .Values.wallet.baseWalletName }}
        - name: MIW_ALLOWLIST_DIDS
          value: {{ .Values.wallet.allowlistDids }}
        - name: MIW_MEMBERSHIP_ORG
          value: {{ .Values.wallet.membershipOrganisation }}
        - name: MIW_OPENAPI_TITLE
          value: {{ .Values.openapi.title }}
        - name: MIW_OPENAPI_DESCRIPTION
          value: {{ .Values.openapi.description }}
        - name: MIW_OPENAPI_TERM_OF_SERVICES_URL
          value: {{ .Values.openapi.termsOfServiceUrl }}
        - name: MIW_OPENAPI_CONTACT_NAME
          value: {{ .Values.openapi.contactName }}
        - name: MIW_OPENAPI_CONTACT_EMAIL
          value: {{ .Values.openapi.contactEmail }}
        - name: MIW_OPENAPI_CONTACT_URL
          value: {{ .Values.openapi.contactUrl }}
        - name: MIW_OPENAPI_LICENSE_NAME
          value: {{ .Values.openapi.licenseName }}
        - name: MIW_OPENAPI_LICENSE_URL
          value: {{ .Values.openapi.licenseUrl }}
        - name: REVOCATION_URL
          value: {{ .Values.revocation.revocationServiceUrl }}
        - name: REVOCATION_CREATE_STATUS_LIST_CREDENTIAL_AT_HOUR
          value: {{ .Values.revocation.refreshHour | quote }}
        - name: LOG_LEVEL_KTOR_ROOT
          value: {{ .Values.logging.ktorRoot }}
        - name: LOG_LEVEL_EXPOSED
          value: {{ .Values.logging.exposed }}
        - name: LOG_LEVEL_ECLIPSE_JETTY
          value: {{ .Values.logging.jetty }}
        - name: LOG_LEVEL_NETTY
          value: {{ .Values.logging.netty }}
        - name: LOG_LEVEL_SERVICES_CALLS
          value: {{ .Values.logging.servicesCalls }}
        - name: WALLET_SERVICE_REQUEST_TIMEOUT
          value: {{ .Values.httpClientTimeout.walletServiceRequest | quote }}
        - name: WALLET_SERVICE_CONNECT_TIMEOUT
          value: {{ .Values.httpClientTimeout.walletServiceConnect | quote }}
        - name: WALLET_SERVICE_SOCKET_TIMEOUT
          value: {{ .Values.httpClientTimeout.walletServiceSocket | quote }}
        - name: BPD_SERVICE_REQUEST_TIMEOUT
          value: {{ .Values.httpClientTimeout.bpdServiceRequest | quote }}
        - name: BPD_SERVICE_CONNECT_TIMEOUT
          value: {{ .Values.httpClientTimeout.bpdServiceConnect | quote }}
        - name: BPD_SERVICE_SOCKET_TIMEOUT
          value: {{ .Values.httpClientTimeout.bpdServiceSocket | quote }}
        - name: REVOCATION_SERVICE_REQUEST_TIMEOUT
          value: {{ .Values.httpClientTimeout.revocationServiceRequest | quote }}
        - name: REVOCATION_SERVICE_CONNECT_TIMEOUT
          value: {{ .Values.httpClientTimeout.revocationServiceConnect | quote }}
        - name: REVOCATION_SERVICE_SOCKET_TIMEOUT
          value: {{ .Values.httpClientTimeout.revocationServiceSocket | quote }}
        - name: WEBHOOK_SERVICE_REQUEST_TIMEOUT
          value: {{ .Values.httpClientTimeout.webhookServiceRequest | quote }}
        - name: WEBHOOK_SERVICE_CONNECT_TIMEOUT
          value: {{ .Values.httpClientTimeout.webhookServiceConnect | quote }}
        - name: WEBHOOK_SERVICE_SOCKET_TIMEOUT
          value: {{ .Values.httpClientTimeout.webhookServiceSocket | quote }}
        resources:
          requests:
            cpu: {{ .Values.resources.managedIdentityWallets.requests.cpu }}
            memory: {{ .Values.resources.managedIdentityWallets.requests.memory }}
          limits:
            cpu: {{ .Values.resources.managedIdentityWallets.limits.cpu }}
            memory: {{ .Values.resources.managedIdentityWallets.limits.memory }}
        ports:
        - containerPort: 8080
      - name: revocation-service
        image: {{ .Values.revocationService.imageName }}:{{ .Values.revocationService.tag }}
        imagePullPolicy: Always
        env:
        - name: QUARKUS_HTTP_PORT
          value: {{ .Values.revocationService.port | quote }}
        - name: QUARKUS_HTTP_ACCESS_LOG_ENABLED
          value: {{ .Values.revocationService.httpAccessLog | quote | default "false" }}
        - name: QUARKUS_DATASOURCE_JDBC_URL
          {{- if .Values.postgresql.useDefaultJdbcUrl }}
          value: {{ include "managed-identity-wallets.jdbcUrl" . }}
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-secret
              key: miw-db-jdbc-url
          {{- end }}
        - name: REVOCATION_BASE_URL
          value: {{ .Values.revocationService.baseUrlForCredentialList }}
        - name: REVOCATION_MIN_ISSUE_INTERVAL
          value: {{ .Values.revocationService.minIssueInterval | quote}}
        - name: QUARKUS_REST_CLIENT_SSI_ISSUANCE_API_URL
          value: {{ .Values.revocationService.clientIssuanceApiUrl }}
        resources:
          requests:
            cpu: {{ .Values.resources.revocationService.requests.cpu }}
            memory: {{ .Values.resources.revocationService.requests.memory }}
          limits:
            cpu: {{ .Values.resources.revocationService.limits.cpu }}
            memory: {{ .Values.resources.revocationService.limits.memory }}
        ports:
        - containerPort: 8086
      - name: endorser-acapy
        image: {{ .Values.acapy.imageName }}:{{ .Values.acapy.tag }}
        env:
        - name: WALLET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-wallet-key
        - name: AGENT_WALLET_SEED
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-agent-wallet-seed
        - name: LEDGER_URL
          value: {{ .Values.acapy.endorser.genesisUrl }}
        - name: LABEL
          value: {{ .Values.acapy.endorser.label }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-jwt-secret
        - name: ACAPY_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-admin-api-key
        - name: LOG_LEVEL
          value: {{ .Values.acapy.endorser.logLevel }}
        - name: ACAPY_ENDPOINT_PORT
          value: {{ .Values.acapy.endorser.endpointPort | quote }}
        - name: ACAPY_ENDPOINT_URL
          value: {{ .Values.acapy.endorser.endpointUrl }}
        - name: ACAPY_ADMIN_PORT
          value: {{ .Values.acapy.endorser.adminPort | quote }}
        - name: DB_HOST
          {{- if .Values.acapypostgresql.enabled }}
          value: {{ include "acapyPostgresContext" (list $ "postgresql.primary.fullname") }}
          {{- else }}
          value: {{ .Values.acapy.endorser.databaseHost }}
          {{- end }}
        - name: DB_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-db-account
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-db-password
        - name: DB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-db-admin
        - name: DB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-endorser-db-admin-password
        resources:
          requests:
            cpu: {{ .Values.resources.endorserAcapy.requests.cpu }}
            memory: {{ .Values.resources.endorserAcapy.requests.memory }}
          limits:
            cpu: {{ .Values.resources.endorserAcapy.limits.cpu }}
            memory: {{ .Values.resources.endorserAcapy.limits.memory }}
        ports:
        - containerPort: 8000
        command: ["/bin/bash"]
        args: ["-c", "aca-py start \
          -e $(ACAPY_ENDPOINT_URL) \
          --auto-provision \
          --inbound-transport http '0.0.0.0' $(ACAPY_ENDPOINT_PORT) \
          --outbound-transport http \
          --admin '0.0.0.0' $(ACAPY_ADMIN_PORT) \
          --wallet-name AcapyBaseEndorserWallet \
          --wallet-type askar \
          --wallet-key $(WALLET_KEY) \
          --wallet-storage-type postgres_storage
          --wallet-storage-config '{\"url\":\"$(DB_HOST):5432\",\"max_connections\":5}'
          --wallet-storage-creds '{\"account\":\"$(DB_ACCOUNT)\",\"password\":\"$(DB_PASSWORD)\",\"admin_account\":\"$(DB_ADMIN_USER)\",\"admin_password\":\"$(DB_ADMIN_PASSWORD)\"}'
          --seed $(AGENT_WALLET_SEED) \
          --genesis-url $(LEDGER_URL) \
          --label $(LABEL) \
          --admin-api-key $(ACAPY_ADMIN_API_KEY) \
          --auto-ping-connection \
          --jwt-secret $(JWT_SECRET) \
          --public-invites \
          --endorser-protocol-role endorser \
          --auto-endorse-transactions \
          --log-level $(LOG_LEVEL)"
        ]
      - name: mt-acapy
        image: {{ .Values.acapy.imageName }}:{{ .Values.acapy.tag }}
        env:
        - name: WALLET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-wallet-key
        - name: AGENT_WALLET_SEED
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-agent-wallet-seed
        - name: LEDGER_URL
          value: {{ .Values.acapy.mt.genesisUrl }}
        - name: LABEL
          value: {{ .Values.acapy.mt.label }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-jwt-secret
        - name: ACAPY_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-admin-api-key
        - name: LOG_LEVEL
          value: {{ .Values.acapy.mt.logLevel }}
        - name: ACAPY_ENDPOINT_PORT
          value: {{ .Values.acapy.mt.endpointPort | quote }}
        - name: ACAPY_ENDPOINT_URL
          value: {{ .Values.acapy.mt.endpointUrl }}
        - name: ACAPY_ADMIN_PORT
          value: {{ .Values.acapy.mt.adminPort | quote }}
        - name: DB_HOST
          {{- if .Values.acapypostgresql.enabled }}
          value: {{ include "acapyPostgresContext" (list $ "postgresql.primary.fullname") }}
          {{- else }}
          value: {{ .Values.acapy.mt.databaseHost }}
          {{- end }}
        - name: DB_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-db-account
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-db-password
        - name: DB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-db-admin
        - name: DB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "managed-identity-wallets.fullname" . }}-acapy
              key: acapy-mt-db-admin-password
        - name: ACAPY_ENDORSER_PUBLIC_DID
          value: {{ .Values.acapy.mt.endorserPublicDid }}
        - name: ACAPY_WEBHOOK_URL
          value: {{ .Values.acapy.mt.webhookUrl }}  
        resources:
          requests:
            cpu: {{ .Values.resources.mtAcapy.requests.cpu }}
            memory: {{ .Values.resources.mtAcapy.requests.memory }}
          limits:
            cpu: {{ .Values.resources.mtAcapy.limits.cpu }}
            memory: {{ .Values.resources.mtAcapy.limits.memory }}
        ports:
        - containerPort: 8003   
        command: ["/bin/bash"]
        args: ["-c", "aca-py start \
          -e $(ACAPY_ENDPOINT_URL) \
          --auto-provision \
          --inbound-transport http '0.0.0.0' $(ACAPY_ENDPOINT_PORT) \
          --outbound-transport http \
          --admin '0.0.0.0' $(ACAPY_ADMIN_PORT) \
          --wallet-name AcapyManagedWallet \
          --wallet-type askar \
          --wallet-key $(WALLET_KEY) \
          --wallet-storage-type postgres_storage
          --wallet-storage-config '{\"url\":\"$(DB_HOST):5432\",\"max_connections\":5}'
          --wallet-storage-creds '{\"account\":\"$(DB_ACCOUNT)\",\"password\":\"$(DB_PASSWORD)\",\"admin_account\":\"$(DB_ADMIN_USER)\",\"admin_password\":\"$(DB_ADMIN_PASSWORD)\"}'
          --seed $(AGENT_WALLET_SEED) \
          --genesis-url $(LEDGER_URL) \
          --label $(LABEL) \
          --admin-api-key $(ACAPY_ADMIN_API_KEY) \
          --auto-ping-connection \
          --jwt-secret $(JWT_SECRET) \
          --multitenant \
          --multitenant-admin \
          --public-invites \
          --webhook-url $(ACAPY_WEBHOOK_URL) \
          --endorser-protocol-role author \
          --endorser-alias endorser \
          --endorser-public-did $(ACAPY_ENDORSER_PUBLIC_DID) \
          --auto-request-endorsement \
          --auto-write-transactions \
          --auto-promote-author-did \
          --log-level $(LOG_LEVEL)"
        ]
