version: '3'

services:

  acapy_container:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5
    container_name: acapy_container
    environment:
      - ACAPY_WALLET_SEED=${SEED}
    entrypoint: /bin/bash
    command: [
       "-c",
       "aca-py start \
        -e http://acapy_container:8001/ \
        --auto-provision \
        --inbound-transport http '0.0.0.0' 8001 \
        --outbound-transport http \
        --wallet-name temp_acapy_wallet \
        --wallet-type indy \
        --wallet-key issuerKeySecret19 \
        --admin-insecure-mode \
        --no-ledger \
        --log-level DEBUG",
    ]
