name: MIW Init DB

on: 
  push:
    paths:
      # this workflow file
      - '.github/workflows/initdb.yml'
      # Docker files
      - 'docker/Dockerfile.import'
      # sqls
      - 'initdb/**'
    branches:
     - main
  workflow_dispatch:

env:
  IMAGE_VERSION: 1.0.0

jobs:
  build:
    # name of the job starts with a "run-level" subordinate to the workflow such that we can
    # depend on them in order to implement workflow dependencies
    name: miw-initdb image built
    runs-on: ubuntu-latest
    # rely on the first job
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}_initdb

    steps:
      # Get the latest sources
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: 'Build and push initdb Docker image'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.import
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}